// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkzwjjdybbsvffqtinsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrendqamR5YmJzdmZmcXRpbnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTE1MDAsImV4cCI6MjA2Nzc2NzUwMH0.BNNaSf6Izc33vTtAgdVpYM6IGKpWYtiDF7h-WjZfkfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});